---
title: "MATH 311 Final Project"
author: "Ben Czekanski & Michael Czekanski"
date: "5/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(data.table)
```

```{r}
flights.bos <- fread("FlightsData0212BOS.csv")
weather.data <- fread("BOSNYCweather0212.csv")


weather <- weather.data %>%
  mutate(DATE = as_date(DATE)) %>%
  mutate(SNOW = as.numeric(SNOW),
         PRCP = as.numeric(PRCP),
         SNWD = as.numeric(SNWD),
         TMIN = as.numeric(TMIN),
         TMAX = as.numeric(TMAX),
         TAVG = as.numeric(TAVG))

weather.nyc <- weather %>%
  filter(NAME == "NY CITY CENTRAL PARK, NY US")

weather.bos <- weather %>%
  filter(NAME == "BOSTON, MA US")
```

##Feature Selection. 
We speculate that the weather in Boston is different from the weather in NYC and that this difference will help us to predict cancellations of flights in Boston. We must test to see if the weather is different in these two cities.
```{r}
hist(weather.bos$TAVG - weather.nyc$TAVG)
```

This is roughly normally distributed so we can perform a t-test.

```{r}
t.test(weather.bos$TAVG - weather.nyc$TAVG)
```

THE AVERAGE TEMPERATURE IS NOT THE SAME.